# Generated by Django 5.2.3 on 2025-07-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('worker', 'Worker'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
